apiVersion: v1
kind: ConfigMap
metadata:
  name: snowflake-mcp-config
  namespace: snowflake-mcp
data:
  # Server configuration
  MCP_SERVER_HOST: "0.0.0.0"
  MCP_SERVER_PORT: "8000"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "structured"
  
  # Connection pool settings
  CONNECTION_POOL_MIN_SIZE: "3"
  CONNECTION_POOL_MAX_SIZE: "10"
  CONNECTION_POOL_MAX_INACTIVE_TIME_MINUTES: "30"
  CONNECTION_POOL_HEALTH_CHECK_INTERVAL_MINUTES: "5"
  CONNECTION_POOL_CONNECTION_TIMEOUT_SECONDS: "30"
  CONNECTION_POOL_RETRY_ATTEMPTS: "3"
  
  # Connection refresh
  SNOWFLAKE_CONN_REFRESH_HOURS: "8"
  
  # Monitoring and metrics
  ENABLE_MONITORING: "true"
  METRICS_PORT: "8001"
  METRICS_PATH: "/metrics"
  HEALTH_CHECK_ENABLED: "true"
  HEALTH_CHECK_PATH: "/health"
  
  # Rate limiting
  ENABLE_RATE_LIMITING: "true"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "120"
  CLIENT_RATE_LIMIT_ENABLED: "true"
  CLIENT_RATE_LIMIT_REQUESTS_PER_MINUTE: "60"
  
  # Security
  ENABLE_SQL_INJECTION_PROTECTION: "true"
  MAX_QUERY_RESULT_ROWS: "10000"
  QUERY_TIMEOUT_SECONDS: "300"
  REQUIRE_SSL: "true"
  
  # Resource limits
  MAX_MEMORY_MB: "1024"
  MAX_CONCURRENT_REQUESTS: "50"
  REQUEST_QUEUE_SIZE: "200"