apiVersion: v1
kind: Secret
metadata:
  name: snowflake-mcp-secrets
  namespace: snowflake-mcp
type: Opaque
stringData:
  # Snowflake connection credentials
  # Base64 encode these values before applying: echo -n "value" | base64
  SNOWFLAKE_ACCOUNT: "your_account.region"
  SNOWFLAKE_USER: "your_username"
  SNOWFLAKE_PASSWORD: "your_password"
  SNOWFLAKE_WAREHOUSE: "your_warehouse"
  SNOWFLAKE_DATABASE: "your_database"
  SNOWFLAKE_SCHEMA: "your_schema"
  
  # Optional: Private key authentication
  # SNOWFLAKE_PRIVATE_KEY: |
  #   -----BEGIN PRIVATE KEY-----
  #   your_private_key_content_here
  #   -----END PRIVATE KEY-----
  # SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: "your_passphrase"
  
  # Optional: API keys for authentication
  # API_KEYS: "key1,key2,key3"